version: 0.8.dev{build}

branches:
  only:
    - master

environment:
  LIBSNDFILE_LOCATION: 'c:\projects\libaudioverse\tmp'
  DEPLOYMENT_HOST: camlorn.net
  DEPLOYMENT_USERNAME: camlorn
  DEPLOYMENT_PASSWORD:
    secure: N+y3x+7kivMfuMDkYVN7CQ==
  PYPI_PASSWORD:
    secure: QCiljp1jjjC1d8WyllDTJg==
  GIT_PASSWORD:
    secure: o8Y0zRhvBAfOEI3iq+Gumw==

init:
  - git config --global core.autocrlf true

clone_folder: c:\projects\libaudioverse

platform:
  - x86
configuration:
  - Release


install:
  - "py -3 -m pip install -U setuptools sphinx"
  #Override pycrypto. 2.6.1 is broken on Python 3 due to an absolute import, so grab the beta:
  - "py -3 -m pip install https://ftp.dlitz.net/pub/dlitz/crypto/pycrypto/pycrypto-2.7a1.tar.gz"
  #Bring in jinja2, pycparser, etc. Paramiko needs pycrypto.
  - "py -3 -m pip install jinja2 pycparser pyyaml paramiko wheel twine pypandoc sphinx"
  #Numpy and scipy, from my server.
  - "py -3 -m pip install http://camlorn.net/appveyor/numpy-1.10.1+mkl-cp35-none-win_amd64.whl"
  - "py -3 -m pip install http://camlorn.net/appveyor/scipy-0.16.0-cp35-none-win_amd64.whl"
  #Minimum stuff for setup.py to build the wheel and docs in a 32-bit Python.
  - 'c:\python35\python -m pip install -U setuptools sphinx pypandoc wheel'
  #This next one gets a bit interesting: we need to download and silently install libsndfile.
  - mkdir tmp
  - cd tmp
  - echo Downloading Libsndfile.
  - mkdir bin
  - cd bin
  - appveyor DownloadFile http://camlorn.net/appveyor/libsndfile32/libsndfile-1.dll
  - cd ..
  - mkdir include
  - cd include
  - appveyor DownloadFile http://camlorn.net/appveyor/libsndfile32/sndfile.h
  - cd ..
  - mkdir lib
  - cd lib
  - appveyor DownloadFile http://camlorn.net/appveyor/libsndfile32/libsndfile-1.lib
  - cd ..
  - appveyor DownloadFile http://camlorn.net/appveyor/pandoc.exe
  - appveyor DownloadFile http://camlorn.net/appveyor/jom.exe
  - cd ..
  - set path=c:\projects\libaudioverse\tmp;%path%
  - gem install asciidoctor


build_script:
  - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\VsDevCmd.bat"'
  #Do this heere so we can be absolutely sure it's set right:
  - 'set include=C:\Libraries\boost_1_59_0;%include%'
  - 'set lib=c:\libraries\boost_1_59_0\lib32-msvc-14.0;%lib%'
  - mkdir build
  - cd build
  #Turn off devmode to make docs be part of all.
  - 'cmake .. -G "NMake Makefiles JOM" -DLIBAUDIOVERSE_DEVMODE:BOOL=OFF -DLIBSNDFILE_LOCATION:STRING="c:/projects/libaudioverse/tmp"'
  - cmake --build . --config Release --target package
  #Go back, so that after_build works.
  - cd ..

after_build:
  #Docs
  - echo Deploying docs.
  - cd tmp
  - 'git clone https://camlorn:%GIT_PASSWORD%@github.com/camlorn/libaudioverse -b gh-pages --single-branch libaudioverse_docs'
  - 'cd libaudioverse_docs\docs'
  - git rm -rf .
  - 'cp ..\..\..\build\documentation\libaudioverse_manual.html libaudioverse_manual.html'
  - 'xcopy /I /Q /E ..\..\..\build\bindings\python\docs\_build\html python'
  #This either commits or doesn't, if it doesn't it's no loss.
  - git add -A .
  - cd ..
  - 'git commit -m "Update documentation for %APPVEYOR_BUILD_VERSION%"'
  - git push
  - cd ../..
  #And then Pypi, etc.
  - echo Uploading Windows build to camlorn.net.
  - py -3 appveyor_upload.py

artifacts:
  - path: 'build\libaudioverse_master.zip'