version: 0.8pre-{build}

branches:
  only:
    - master

environment:
  LIBSNDFILE_LOCATION: 'c:\projects\libaudioverse\tmp'
  DEPLOYMENT_HOST: camlorn.net
  DEPLOYMENT_USERNAME: camlorn
  DEPLOYMENT_PASSWORD:
    secure: N+y3x+7kivMfuMDkYVN7CQ==
init:
  - git config --global core.autocrlf true

clone_folder: c:\projects\libaudioverse
shallow_clone: true
clone_depth: 5

platform:
  - x86
configuration:
  - Release


install:
  #First, we need to get ourselves into a miniconda environment.
  - "set PATH=C:\\Miniconda;C:\\Miniconda\\Scripts;%PATH%"
  #Alwways confirm and don't change the prompt.
  - conda config --set always_yes yes --set changeps1 no
  #Bring in latest conda packages.
  - conda update -q conda
  - conda info -a
  - "conda create -q -n lav-environment python=3.5 numpy scipy"
  - activate lav-environment
  #Bring in jinja2, pycparser, etc.
  - "pip install jinja2 pycparser pyyaml paramiko"
  #Override pycrypto. 2.6.1 is broken on Python 3 due to an absolute import, so grab the beta:
  - "pip install https://ftp.dlitz.net/pub/dlitz/crypto/pycrypto/pycrypto-2.7a1.tar.gz"
  #This next one gets a bit interesting: we need to download and silently install libsndfile.
  - mkdir tmp
  - cd tmp
  - echo Downloading Libsndfile.
  - mkdir bin
  - cd bin
  - appveyor DownloadFile http://camlorn.net/appveyor/libsndfile32/libsndfile-1.dll
  - cd ..
  - mkdir include
  - cd include
  - appveyor DownloadFile http://camlorn.net/appveyor/libsndfile32/sndfile.h
  - cd ..
  - mkdir lib
  - cd lib
  - appveyor DownloadFile http://camlorn.net/appveyor/libsndfile32/libsndfile-1.lib
  - cd ../..
  - gem install asciidoctor


build_script:
  - mkdir build
  - cd build
  #Turn off devmode to make docs be part of all.
  - 'cmake .. -DLIBAUDIOVERSE_DEVMODE:BOOL=OFF -DLIBSNDFILE_LOCATION:STRING="c:/projects/libaudioverse/tmp" -DLIBAUDIOVERSE_IN_CI:BOOL=ON'
  #-m is parallel build.
  - cmake --build . --config Release --target package -- /m
  #Go back, so that after_build works.
  - cd ..

after_build:
  - echo Uploading Windows build to camlorn.net.
  - python appveyor_upload.py

artifacts:
  - path: 'build\libaudioverse_master.zip'